name: Test72
favicon: null
layout_spectrum: 0.9201248902827501
typography_spectrum: 0.41506788576953113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5441619937773794
  lightness: 0.5319669113960117
  saturation: 0.508870217949152
  rhythmicContrast: 0.6449738794472069
purpose: []
